import './globals.css';
import { Inter } from 'next/font/google';

import styles from './layout.module.css';
import Title from './Title';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Drug Overflow',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={[inter.className, styles.body].join(' ')}>
        <Title />
        {children}
      </body>
    </html>
  );
}
